lcgcmt_installarea=without_installarea
CMTPATH=/junofs/users/yuansc/bes3_add_layer/code/boss/workarea:/cvmfs/bes3.ihep.ac.cn/bes3sw/Boss/7.0.5:/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/ExternalLib/gaudi/GAUDI_v23r9:/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/ExternalLib/LCGCMT/LCGCMT_65a
CMT_tag=$(tag)
CMTROOT=/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/contrib/CMT/v1r25
CMT_root=/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/contrib/CMT/v1r25
CMTVERSION=v1r25
CMT_offset=/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/contrib
cmt_hardware_query_command=uname -m
cmt_hardware=`$(cmt_hardware_query_command)`
cmt_system_version_query_command=${CMTROOT}/mgr/cmt_linux_version.sh | ${CMTROOT}/mgr/cmt_filter_version.sh
cmt_system_version=`$(cmt_system_version_query_command)`
cmt_compiler_version_query_command=${CMTROOT}/mgr/cmt_gcc_version.sh | ${CMTROOT}/mgr/cmt_filter3_version.sh
cmt_compiler_version=`$(cmt_compiler_version_query_command)`
PATH=/junofs/users/yuansc/bes3_add_layer/code/boss/workarea/InstallArea/${CMTCONFIG}/bin:/cvmfs/bes3.ihep.ac.cn/bes3sw/Boss/7.0.5/InstallArea/${CMTCONFIG}/bin:/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/ExternalLib/gaudi/GAUDI_v23r9/InstallArea/${CMTCONFIG}/bin:/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/contrib/CMT/v1r25/${CMTBIN}:/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/ExternalLib/gaudi/GAUDI_v23r9/InstallArea/x86_64-slc6-gcc46-opt/scripts:/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/ExternalLib/external/ROOT/5.34.09/x86_64-slc6-gcc46-opt/root/bin:/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/ExternalLib/external/xrootd/3.2.7/x86_64-slc6-gcc46-opt/bin:/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/ExternalLib/external/gccxml/0.9.0_20120309p2/x86_64-slc6-gcc46-opt/bin:/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/ExternalLib/external/tcmalloc/1.7p3/x86_64-slc6-gcc46-opt/bin:/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/ExternalLib/external/Python/2.7.3/x86_64-slc6-gcc46-opt/bin:/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/ExternalLib/external/sqlite/3070900/x86_64-slc6-gcc46-opt/bin:/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/ExternalLib/external/castor/2.1.13-6/x86_64-slc6-gcc46-opt/usr/bin:/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/ExternalLib/external/mysql/5.5.14/x86_64-slc6-gcc46-opt/bin:/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/ExternalLib/external/XercesC/3.1.1p1/x86_64-slc6-gcc46-opt/bin:/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/ExternalLib/external/pytools/1.8_python2.7/x86_64-slc6-gcc46-opt/bin:/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/contrib/gcc/4.6.3/x86_64-slc6/bin:/afs/ihep.ac.cn/soft/common/sysgroup/hep_job/bin:/usr/local/bin:/usr/bin:/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/ExternalLib/external/cernlib/2006a/x86_64-slc6-gcc46-opt/bin
CLASSPATH=/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/contrib/CMT/v1r25/java
debug_option=-g
cc=gcc
ccomp=$(cc) -c $(includes) $(cdebugflags) $(cflags) $(pp_cflags)
clink=$(cc) $(clinkflags) $(cdebugflags)
ppcmd=-I
preproc=c++ -MD -c 
cpp=c++
cppflags=-pipe -ansi -pedantic -W -Wall -Wwrite-strings -Wpointer-arith -Woverloaded-virtual 
pp_cppflags=-D_GNU_SOURCE
cppcomp=$(cpp) -c $(includes) $(cppdebugflags) $(cppflags) $(pp_cppflags)
cpplink=$(cpp) $(cpplinkflags) $(cppdebugflags)
for=g77
fflags=$(debug_option)
fcomp=$(for) -c $(fincludes) $(fflags) $(pp_fflags)
flink=$(for) $(flinkflags)
javacomp=javac -classpath $(src):$(CLASSPATH) 
javacopy=cp
jar=jar
X11_cflags=-I/usr/include
Xm_cflags=-I/usr/include
X_linkopts=-L/usr/X11R6/lib -lXm -lXt -lXext -lX11 -lm
lex=lex $(lexflags)
yaccflags= -l -d 
yacc=yacc $(yaccflags)
ar=ar cr
ranlib=ranlib
make_shlib=${CMTROOT}/mgr/cmt_make_shlib_common.sh extract
shlibsuffix=so
shlibbuilder=g++ $(cmt_installarea_linkopts) 
shlibflags=-shared
symlink=/bin/ln -fs 
symunlink=/bin/rm -f 
library_install_command=${symlink}
build_library_links=$(cmtexe) build library_links -tag=$(tags)
remove_library_links=$(cmtexe) remove library_links -tag=$(tags)
cmtexe=${CMTROOT}/${CMTBIN}/cmt.exe
build_prototype=$(cmtexe) build prototype
build_dependencies=$(cmtexe) -tag=$(tags) build dependencies
build_triggers=$(cmtexe) build triggers
format_dependencies=${CMTROOT}/mgr/cmt_format_deps.sh
implied_library_prefix=-l
SHELL=/bin/sh
q="
src=../src/
doc=../doc/
inc=../src/
mgr=../mgr/
application_suffix=.exe
library_prefix=lib
unlock_command=rm -rf 
lock_name=cmt
lock_suffix=.lock
lock_file=${lock_name}${lock_suffix}
svn_checkout_command=python ${CMTROOT}/mgr/cmt_svn_checkout.py 
gmake_hosts=lx1 rsplus lxtest as7 dxplus ax7 hp2 aleph hp1 hpplus papou1-fe atlas
make_hosts=virgo-control1 rio0a vmpc38a
everywhere=hosts
install_command=cp 
uninstall_command=/bin/rm -f 
cmt_installarea_command=ln -fs 
cmt_uninstallarea_command=/bin/rm -f 
cmt_install_area_command=$(cmt_installarea_command)
cmt_uninstall_area_command=$(cmt_uninstallarea_command)
cmt_install_action=$(CMTROOT)/mgr/cmt_install_action.sh
cmt_installdir_action=$(CMTROOT)/mgr/cmt_installdir_action.sh
cmt_uninstall_action=$(CMTROOT)/mgr/cmt_uninstall_action.sh
cmt_uninstalldir_action=$(CMTROOT)/mgr/cmt_uninstalldir_action.sh
mkdir=mkdir
cmt_installarea_prefix=InstallArea
CMT_PATH_remove_regexp=/[^/]*/
CMT_PATH_remove_share_regexp=/share/
NEWCMTCONFIG=x86_64-slc79-gcc463
tag=x86_64-slc6-gcc46-opt
package=cmt_standalone
version=v0
PACKAGE_ROOT=$(CMT_STANDALONEROOT)
srcdir=.
bin=./
javabin=./
BIN=/./
cmt_installarea_paths= $(cmt_installarea_prefix)/$(CMTCONFIG)/bin $(GAUDI_installarea_prefix)/$(CMTCONFIG)/lib $(GAUDI_installarea_prefix)/share/lib $(GAUDI_installarea_prefix)/share/bin $(BOSS_installarea_prefix)/$(CMTCONFIG)/lib $(BOSS_installarea_prefix)/share/lib $(BOSS_installarea_prefix)/share/bin $(boss_installarea_prefix)/$(CMTCONFIG)/lib $(boss_installarea_prefix)/share/lib $(boss_installarea_prefix)/share/bin
use_linkopts= $(cmt_installarea_linkopts)   $(cmt_standalone_linkopts) 
LCGCMT_installarea_prefix=$(cmt_installarea_prefix)
LCGCMT_installarea_prefix_remove=$(LCGCMT_installarea_prefix)
LD_LIBRARY_PATH=/junofs/users/yuansc/bes3_add_layer/code/boss/workarea/InstallArea/${CMTCONFIG}/lib:/cvmfs/bes3.ihep.ac.cn/bes3sw/Boss/7.0.5/InstallArea/${CMTCONFIG}/lib:/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/ExternalLib/gaudi/GAUDI_v23r9/InstallArea/${CMTCONFIG}/lib:/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/ExternalLib/external/Boost/1.50.0_python2.7/x86_64-slc6-gcc46-opt/lib:/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/ExternalLib/external/ROOT/5.34.09/x86_64-slc6-gcc46-opt/root/lib:/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/ExternalLib/external/xrootd/3.2.7/x86_64-slc6-gcc46-opt/lib64:/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/ExternalLib/external/CLHEP/String/String-00-00-05/x86_64-slc6-gcc46-opt:/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/ExternalLib/external/CLHEP/Alist/Alist-00-00-06/x86_64-slc6-gcc46-opt:/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/ExternalLib/external/HepPDT/2.06.01/x86_64-slc6-gcc46-opt/lib:/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/ExternalLib/external/HepMC/2.06.08/x86_64-slc6-gcc46-opt/lib:/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/ExternalLib/external/clhep/2.0.4.5/x86_64-slc6-gcc46-opt/lib:/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/ExternalLib/external/tcmalloc/1.7p3/x86_64-slc6-gcc46-opt/lib:/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/ExternalLib/external/libunwind/5c2cade/x86_64-slc6-gcc46-opt/lib:/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/ExternalLib/external/sqlite/3070900/x86_64-slc6-gcc46-opt/lib:/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/ExternalLib/external/castor/2.1.13-6/x86_64-slc6-gcc46-opt/usr/lib64:/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/ExternalLib/external/mysql/5.5.14/x86_64-slc6-gcc46-opt/lib:/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/ExternalLib/external/XercesC/3.1.1p1/x86_64-slc6-gcc46-opt/lib:/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/ExternalLib/external/pytools/1.8_python2.7/x86_64-slc6-gcc46-opt/lib:/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/ExternalLib/external/lapack/3.4.0/x86_64-slc6-gcc46-opt/lib:/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/ExternalLib/external/blas/20110419/x86_64-slc6-gcc46-opt/lib:/usr/lib:/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/contrib/gcc/4.6.3/x86_64-slc6/lib64:/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/contrib/gcc/4.6.3/x86_64-slc6/lib:/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/contrib/compat/lib64:/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/contrib/compat/usr/lib64:/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/ExternalLib/external/BesGDML/2.8.0/x86_64-slc6-gcc46-opt/lib:/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/ExternalLib/external/DIM/dim_v19r11/x86_64-slc6-gcc46-opt/linux:/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/ExternalLib/external/xmlrpc-c/xmlrpc-c-1.25.27/x86_64-slc6-gcc46-opt/lib:/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/ExternalLib/external/genbes/genbes-00-00-11/x86_64-slc6-gcc46-opt:/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/ExternalLib/external/Python/2.7.3/x86_64-slc6-gcc46-opt/lib:/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/ExternalLib/external/geant4/4.9.3p01/x86_64-slc6-gcc46-opt/lib/Linux-g++
GAUDI_installarea_prefix=$(cmt_installarea_prefix)
GAUDI_installarea_prefix_remove=$(GAUDI_installarea_prefix)
BOSS_installarea_prefix=$(cmt_installarea_prefix)
BOSS_installarea_prefix_remove=$(BOSS_installarea_prefix)
boss_installarea_prefix=$(cmt_installarea_prefix)
boss_installarea_prefix_remove=$(boss_installarea_prefix)
cmt_installarea_linkopts= -L/junofs/users/yuansc/bes3_add_layer/code/boss/workarea/$(boss_installarea_prefix)/$(CMTCONFIG)/lib  -L/cvmfs/bes3.ihep.ac.cn/bes3sw/Boss/7.0.5/$(BOSS_installarea_prefix)/$(CMTCONFIG)/lib  -L/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/ExternalLib/gaudi/GAUDI_v23r9/$(GAUDI_installarea_prefix)/$(CMTCONFIG)/lib 
CMTINSTALLAREA=/junofs/users/yuansc/bes3_add_layer/code/boss/workarea/$(cmt_installarea_prefix)
use_requirements=requirements $(CMT_root)/mgr/requirements 
use_includes= 
use_fincludes= $(use_includes)
use_stamps=  $(cmt_standalone_stamps) 
use_cflags=  $(cmt_standalone_cflags) 
use_pp_cflags=  $(cmt_standalone_pp_cflags) 
use_cppflags=  $(cmt_standalone_cppflags) 
use_pp_cppflags=  $(cmt_standalone_pp_cppflags) 
use_fflags=  $(cmt_standalone_fflags) 
use_pp_fflags=  $(cmt_standalone_pp_fflags) 
includes= $(ppcmd)"$(srcdir)" $(use_includes)
fincludes= $(includes)
make_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
constituents= 
all_constituents= $(constituents)
constituentsclean= 
all_constituentsclean= $(constituentsclean)
cmt_actions_constituents= make 
cmt_actions_constituentsclean= makeclean 
