lcgcmt_installarea=without_installarea
CMTPATH=/home/lliu/boss/Workarea-6.6.4.p01:/software/STCF/stcf1.0.0:/software/BES/bes6.6.4.p01/dist/6.6.4.p01:/software/BES/bes6.6.4.p01/Gaudi/GAUDI_v21r6/x86_64-slc5-gcc43-clhep2.0.4.5:/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5
CMT_tag=$(tag)
CMTROOT=/software/BES/bes6.6.4.p01/CMT/v1r20p20090520
CMT_root=/software/BES/bes6.6.4.p01/CMT/v1r20p20090520
CMTVERSION=v1r20p20090520
cmt_hardware_query_command=uname -m
cmt_hardware=`$(cmt_hardware_query_command)`
cmt_system_version_query_command=${CMTROOT}/mgr/cmt_linux_version.sh | ${CMTROOT}/mgr/cmt_filter_version.sh
cmt_system_version=`$(cmt_system_version_query_command)`
cmt_compiler_version_query_command=${CMTROOT}/mgr/cmt_gcc_version.sh | ${CMTROOT}/mgr/cmt_filter3_version.sh
cmt_compiler_version=`$(cmt_compiler_version_query_command)`
PATH=/home/lliu/boss/Workarea-6.6.4.p01/InstallArea/share/bin:/software/STCF/stcf1.0.0/InstallArea/share/bin:/software/BES/bes6.6.4.p01/dist/6.6.4.p01/InstallArea/share/bin:/software/BES/bes6.6.4.p01/Gaudi/GAUDI_v21r6/x86_64-slc5-gcc43-clhep2.0.4.5/InstallArea/share/bin:/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5/InstallArea/share/bin:/home/lliu/boss/Workarea-6.6.4.p01/InstallArea/scripts:/software/STCF/stcf1.0.0/InstallArea/scripts:/software/BES/bes6.6.4.p01/dist/6.6.4.p01/InstallArea/scripts:/software/BES/bes6.6.4.p01/Gaudi/GAUDI_v21r6/x86_64-slc5-gcc43-clhep2.0.4.5/InstallArea/scripts:/home/lliu/boss/Workarea-6.6.4.p01/InstallArea/${CMTCONFIG}/bin:/software/STCF/stcf1.0.0/InstallArea/${CMTCONFIG}/bin:/software/BES/bes6.6.4.p01/dist/6.6.4.p01/InstallArea/${CMTCONFIG}/bin:/software/BES/bes6.6.4.p01/Gaudi/GAUDI_v21r6/x86_64-slc5-gcc43-clhep2.0.4.5/InstallArea/${CMTCONFIG}/bin:/software/BES/bes6.6.4.p01/lcg/external/pcre/4.4/x86_64-slc5-gcc43-opt/bin:/software/BES/bes6.6.4.p01/lcg/external/ROOT/5.24.00b/x86_64-slc5-gcc43-opt/root/bin:/software/BES/bes6.6.4.p01/lcg/external/gccxml/0.9.0_20090601/x86_64-slc5-gcc43-opt/bin:/software/BES/bes6.6.4.p01/lcg/external/tcmalloc/1.4/x86_64-slc5-gcc43-opt/bin:/software/BES/bes6.6.4.p01/lcg/external/Python/2.5.4p2/x86_64-slc5-gcc43-opt/bin:/software/BES/bes6.6.4.p01/CMT/v1r20p20090520/${CMTBIN}:/software/BES/bes6.6.4.p01/lcg/external/sqlite/3.6.11/x86_64-slc5-gcc43-opt/bin:/software/BES/bes6.6.4.p01/lcg/external/mysql/5.0.18/x86_64-slc5-gcc43-opt/bin:/software/BES/bes6.6.4.p01/lcg/external/XercesC/2.8.0/x86_64-slc5-gcc43-opt/bin:/software/BES/bes6.6.4.p01/lcg/external/castor/2.1.8-10/x86_64-slc5-gcc43-opt/usr/bin:/home/lliu/.software/bin:/home/lliu/.software/git/bin:/software/BES/bes6.6.4.p01/contrib/x86_64-slc5-gcc43-opt/bin:/software/BES/bes6.6.4.p01/contrib/gcc43/bin:/usr/kerberos/bin:/bin:/usr/bin:/usr/X11R6/bin:/software/BES/bes6.6.4.p01/sw/contrib/DAWN/3.85/bin/Linux:/software/BES/bes6.6.4.p01/sw/contrib/DAWN/3.85/../bin/Linux:/software/BES/bes6.6.4.p01/sw/contrib/DAVID/1.34/bin/Linux:/software/BES/bes6.6.4.p01/lcg/external/cernlib/2006a/x86_64-slc5-gcc43-opt/bin
CLASSPATH=/software/BES/bes6.6.4.p01/CMT/v1r20p20090520/java
debug_option=-g
cc=$(cc_name)
cflags= -fmessage-length=0 -fPIC 
ccomp=$(cc) -c $(includes) $(cdebugflags) $(cflags) $(pp_cflags)
clink=$(cc) $(clinkflags) $(cdebugflags)
vsCONFIG=Release
vsOptimize=2
ppcmd=-I
preproc=c++ -MD -c 
cpp=$(cpp_name)
cppdebugflags=$(cppoptimized_s)
cppflags= -fmessage-length=0     -Wall -Wextra -pthread  -Wno-deprecated -Wno-empty-body -D_GNU_SOURCE -pthread -pipe -ansi -pedantic -W -Wall -Wwrite-strings -Wpointer-arith -Woverloaded-virtual -Wno-long-long  -fPIC -march=x86-64 -mtune=x86-64 -pedantic-errors -O2
pp_cppflags=-D_GNU_SOURCE -DGAUDI_V20_COMPAT 
cppcomp=$(cpp) -c $(includes) $(cppdebugflags) $(cppflags) $(pp_cppflags)
cpplinkflags=-Wl,-Bdynamic $(linkdebugflags) -ldl  -Wl,--no-undefined -Wl,--export-dynamic 
cpplink=$(cpp) $(cpplinkflags)
for=$(for_name)
fflags=-fmessage-length=0 -O2   -fPIC -pipe -fno-second-underscore -Wall -W -Wsurprising -fPIC 
fcomp=$(for) -c $(fincludes) $(fdebugflags) $(fflags) $(pp_fflags)
flink=$(for) $(flinkflags)
javacomp=javac -classpath $(src):$(CLASSPATH) 
javacopy=cp
jar=jar
X11_cflags=-I/usr/include
Xm_cflags=-I/usr/include
X_linkopts=-L/usr/X11R6/lib -lXm -lXt -lXext -lX11 -lm
lex=lex $(lexflags)
yaccflags= -l -d 
yacc=yacc $(yaccflags)
ar=ar cr
ranlib=ranlib
make_shlib=${CMTROOT}/mgr/cmt_make_shlib_common.sh extract
shlibsuffix=so
shlibbuilder=$(cpp) $(cmt_installarea_linkopts) 
shlibflags=-shared
symlink=symlink.sh
symunlink=/bin/rm -f 
library_install_command=python $(GaudiPolicy_root)/scripts/install.py -xCVS -x*~ -x*.stamp -x*.bak -x.* -x*.pyc -x*.pyo -s --log=./install.history 
build_library_links=$(cmtexe) build library_links -tag=$(tags)
remove_library_links=$(cmtexe) remove library_links -tag=$(tags)
cmtexe=${CMTROOT}/${CMTBIN}/cmt.exe
build_prototype=$(cmtexe) build prototype
build_dependencies=$(cmtexe) -tag=$(tags) build dependencies
build_triggers=$(cmtexe) build triggers
format_dependencies=${CMTROOT}/mgr/cmt_format_deps.sh
implied_library_prefix=-l
SHELL=/bin/sh
q="
src=../src/
doc=../doc/
inc=../src/
mgr=../cmt/
application_suffix=.exe
library_prefix=lib
lock_command=lockfile 
unlock_command=rm -rf 
lock_name=cmt
lock_suffix=.lock
lock_file=${lock_name}${lock_suffix}
svn_checkout_command=/usr/bin/python ${CMTROOT}/mgr/cmt_svn_checkout.py 
MAKEFLAGS= --no-print-directory  --no-print-directory 
gmake_hosts=lx1 rsplus lxtest as7 dxplus ax7 hp2 aleph hp1 hpplus papou1-fe atlas
make_hosts=virgo-control1 rio0a vmpc38a
everywhere=hosts
GUID_all={8BC9CEB8-8B4A-11D0-8D11-00A0C91BC955}
package_GUID={8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}
install_command=cp -R 
uninstall_command=python $(GaudiPolicy_root)/scripts/install.py -u --log=./install.history 
cmt_installarea_command=python $(GaudiPolicy_root)/scripts/install.py -xCVS -x*~ -x*.stamp -x*.bak -x.* -x*.pyc -x*.pyo -s --log=./install.history 
cmt_uninstallarea_command=/bin/rm -f 
cmt_install_area_command=$(symlink_command)
cmt_uninstall_area_command=$(uninstall_command)
cmt_install_action=$(CMTROOT)/mgr/cmt_install_action.sh
cmt_installdir_action=$(CMTROOT)/mgr/cmt_installdir_action.sh
cmt_uninstall_action=$(CMTROOT)/mgr/cmt_uninstall_action.sh
cmt_uninstalldir_action=$(CMTROOT)/mgr/cmt_uninstalldir_action.sh
mkdir=mkdir
cmt_installarea_prefix=InstallArea
CMT_PATH_remove_regexp=/[^/]*/
CMT_PATH_remove_share_regexp=/share/
NEWCMTCONFIG=x86_64-sl57-gcc432
McDecayModeSvc_tag=$(tag)
MCDECAYMODESVCROOT=/home/lliu/boss/Workarea-6.6.4.p01/Analysis/McDecayModeSvc/McDecayModeSvc-00-00-01
McDecayModeSvc_root=/home/lliu/boss/Workarea-6.6.4.p01/Analysis/McDecayModeSvc/McDecayModeSvc-00-00-01
MCDECAYMODESVCVERSION=McDecayModeSvc-00-00-01
McDecayModeSvc_cmtpath=/home/lliu/boss/Workarea-6.6.4.p01
McDecayModeSvc_offset=Analysis
McDecayModeSvc_project=boss
McDecayModeSvc_project_release=Workarea-6.6.4.p01
BesPolicy_tag=$(tag)
BESPOLICYROOT=/software/BES/bes6.6.4.p01/dist/6.6.4.p01/BesPolicy/BesPolicy-01-05-03
BesPolicy_root=/software/BES/bes6.6.4.p01/dist/6.6.4.p01/BesPolicy/BesPolicy-01-05-03
BESPOLICYVERSION=BesPolicy-01-05-03
BesPolicy_cmtpath=/software/BES/bes6.6.4.p01/dist/6.6.4.p01
BesPolicy_project=BOSS
BesPolicy_project_release=6.6.4.p01
BesCxxPolicy_tag=$(tag)
BESCXXPOLICYROOT=/software/BES/bes6.6.4.p01/dist/6.6.4.p01/BesCxxPolicy/BesCxxPolicy-00-01-01
BesCxxPolicy_root=/software/BES/bes6.6.4.p01/dist/6.6.4.p01/BesCxxPolicy/BesCxxPolicy-00-01-01
BESCXXPOLICYVERSION=BesCxxPolicy-00-01-01
BesCxxPolicy_cmtpath=/software/BES/bes6.6.4.p01/dist/6.6.4.p01
BesCxxPolicy_project=BOSS
BesCxxPolicy_project_release=6.6.4.p01
GaudiPolicy_tag=$(tag)
GAUDIPOLICYROOT=/software/BES/bes6.6.4.p01/Gaudi/GAUDI_v21r6/x86_64-slc5-gcc43-clhep2.0.4.5/GaudiPolicy
GaudiPolicy_root=/software/BES/bes6.6.4.p01/Gaudi/GAUDI_v21r6/x86_64-slc5-gcc43-clhep2.0.4.5/GaudiPolicy
GAUDIPOLICYVERSION=v10r4
GaudiPolicy_cmtpath=/software/BES/bes6.6.4.p01/Gaudi/GAUDI_v21r6/x86_64-slc5-gcc43-clhep2.0.4.5
GaudiPolicy_project=GAUDI
GaudiPolicy_project_release=x86_64-slc5-gcc43-clhep2.0.4.5
LCG_Settings_tag=$(tag)
LCG_SETTINGSROOT=/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5/LCG_Settings
LCG_Settings_root=/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5/LCG_Settings
LCG_SETTINGSVERSION=v1
LCG_Settings_cmtpath=/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5
LCG_Settings_project=LCGCMT
LCG_Settings_project_release=LCGCMT_57a_clhep2.0.4.5
LCG_SettingsCompat_use=LCG_SettingsCompat
LCG_SettingsCompat_tag=$(tag)
LCG_SETTINGSCOMPATROOT=/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5/LCG_SettingsCompat
LCG_SettingsCompat_root=/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5/LCG_SettingsCompat
LCG_SETTINGSCOMPATVERSION=v1
LCG_SettingsCompat_cmtpath=/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5
LCG_SettingsCompat_project=LCGCMT
LCG_SettingsCompat_project_release=LCGCMT_57a_clhep2.0.4.5
SITEROOT=/software/BES/bes6.6.4.p01
LCG_home=${SITEROOT}/lcg
LCG_external=$(LCG_home)/external
LCG_contrib=$(LCG_home)/contrib
LCG_releases=$(LCG_home)/external
LCG_basesystem=x86_64-slc5-gcc43
LCG_system=$(LCG_basesystem)-opt
LCG_platform=$(LCG_system)
LCG_hostos=x86_64-slc5
LCG_hostarch=x86_64
ATLAS_TAGS_MAP=none
host_compiler=gcc43
host_arch=x86_64
host_os=linux
host_cmtconfig=x86_64-linux-gcc43-opt
unixdirname=lib64
gcc_config_version=4.3.2
gcc_native_version=$(gcc_config_version)
gcc_home=$(LCG_external)/gcc/$(gcc_native_version)/$(LCG_hostos)
llvm_native_version=$(llvm_config_version)
llvm_home=$(LCG_external)/llvm/$(llvm_native_version)/$(LCG_hostos)
icc_native_version=$(icc_config_version)
intelplat=intel64
intel_home=/afs/cern.ch/sw/IntelSoftware/linux
icc_home=$(intel_home)/x86_64/Compiler/$(icc_native_version)
icc_c_home=$(icc_home)/081
icc_f_home=$(icc_home)/083
cc_name=gcc
cpp_name=g++
cpplinkname=$(cpp)
for_name=gfortran
Python_tag=$(tag)
PYTHONROOT=/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5/LCG_Interfaces/Python
Python_root=/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5/LCG_Interfaces/Python
PYTHONVERSION=v1
Python_cmtpath=/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5
Python_offset=LCG_Interfaces
Python_project=LCGCMT
Python_project_release=LCGCMT_57a_clhep2.0.4.5
LCG_Configuration_tag=$(tag)
LCG_CONFIGURATIONROOT=/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5/LCG_Configuration
LCG_Configuration_root=/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5/LCG_Configuration
LCG_CONFIGURATIONVERSION=v1
LCG_Configuration_cmtpath=/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5
LCG_Configuration_project=LCGCMT
LCG_Configuration_project_release=LCGCMT_57a_clhep2.0.4.5
LCG_config_version=57a
COOL_config_version=COOL_2_8_3
CORAL_config_version=CORAL_2_3_4
POOL_config_version=POOL_2_9_3
RELAX_config_version=RELAX_1_2_0
ROOT_config_version=5.24.00b
AIDA_config_version=3.2.1
4suite_config_version=1.0.2
bjam_config_version=3.1.13
blas_config_version=20070405
Boost_config_version=1.39.0
Boost_file_version=1_39
bz2lib_config_version=1.0.2
CASTOR_config_version=2.1.8-10
cernlib_config_version=2006a
cgal_config_version=3.3.1
cgsigsoap_config_version=1.3.3-1
CLHEP_config_version=2.0.4.5
cmake_config_version=2.6.4
cmt_config_version=v1r20p20081118
coin3d_config_version=2.4.6
CppUnit_config_version=1.12.1_p1
cx_oracle_config_version=5.0.1
Cygwin_config_version=1.5
david_config_version=1_36a
dawn_config_version=3_88a
dcache_client_config_version=1.9.3
dcache_config_version_dcap=1.9.3-0
dcache_config_version_srm=1.8.0-15p7
doxygen_config_version=1.5.9
dpm_config_version=1.7.2-5sec
EDGRLS_config_version=2.3.3
Expat_config_version=2.0.0
fftw_config_version=3.1.2
Frontier_Client_config_version=2.7.11
fastjet_config_version=2.4.1
GCCXML_config_version=0.9.0_20090601
gfal_config_version=1.11.8-2
globus_config_version=4.0.3-VDT-1.6.0
graphviz_config_version=2.22.2
GSL_config_version=1.10
HepMC_config_version=2.03.11
HepPDT_config_version=2.05.04
HippoDraw_config_version=1.9.0
ipython_config_version=0.8.4
javasdk_config_version=1.5.0
javajni_config_version=$(javasdk_config_version)
kcachegrind_config_version=0.4.6
ktjet_config_version=1.08
lapack_config_version=3.1.1
lcgdmcommon_config_version=1.7.2-1sec
lcginfosites_config_version=2.6.2-1
lcgutils_config_version=1.7.6-1
lcov_config_version=1.7
lfc_config_version=1.7.2-1sec
libsvm_config_version=2.86
libunwind_config_version=0.99
MathLib_config_version=1_0_0
myproxy_config_version=3.6-VDT-1.6.0
mysql_config_version=5.0.18
mysql_python_config_version=1.2.2
mysqlpp_config_version=1.7.40
oracle_config_version=11.2.0.1.0
PCRE_config_version=4.4
processing_config_version=0.51
pydot_config_version=1.0.2
Python_config_version=2.5.4p2
pyqt_config_version=4.4.3
pyqt_compat_config_version=4.4.3
pyparsing_config_version=1.5.1
pyxml_config_version=0.8.4p1
QMtest_config_version=2.4p1
Qt_config_version=4.4.2
qwt_config_version=5.1.1
readline_config_version=2.5.1p1
roofit_config_version=3.10p1
rx_config_version=1.5
scons_config_version=0.96.1
sip_config_version=4.7.7
siscone_config_version=1.3.3
slc4_compat_config_version=1.0
soqt_config_version=1.4.1
sqlite_config_version=3.6.11
tcmalloc_config_version=1.4
tcsh_config_version=6.16.00
uuid_config_version=1.38
valgrind_config_version=3.5.0
vdt_config_version=1.2.3_globusrls215b
vomsapic_config_version=1.8.9-2
vomsapicpp_config_version=1.8.9-2
vomsapi_noglobus_config_version=1.9.8-1
vomsclients_config_version=1.8.9-2
XercesC_config_version=2.8.0
XercesC_file_version=2_8_0
zlib_config_version=1.2.3
pcre_config_version=4.4
Python_native_version=$(Python_config_version)
Python_home=${LCG_external}/Python/$(Python_native_version)/$(LCG_system)
Python_inc=$(Python_home)/include/python$(Python_version)
Python_config_version_twodigit=2.5
Python_version=$(Python_config_version_twodigit)
Python_libversion_cmd=python -c "print ''.join('$(Python_config_version)'.split('.')[:2])"
Python_libversion=$(Python_config_version_twodigit)
LD_LIBRARY_PATH=/lib:/home/lliu/boss/Workarea-6.6.4.p01/InstallArea/${CMTCONFIG}/lib:/software/STCF/stcf1.0.0/InstallArea/${CMTCONFIG}/lib:/software/BES/bes6.6.4.p01/dist/6.6.4.p01/InstallArea/${CMTCONFIG}/lib:/software/BES/bes6.6.4.p01/Gaudi/GAUDI_v21r6/x86_64-slc5-gcc43-clhep2.0.4.5/InstallArea/${CMTCONFIG}/lib:${STRING_DIR}/x86_64-slc5-gcc43-opt:${ALIST_DIR}/x86_64-slc5-gcc43-opt:/software/BES/bes6.6.4.p01/lcg/external/HepPDT/2.05.04/x86_64-slc5-gcc43-opt/lib:/software/BES/bes6.6.4.p01/lcg/external/HepMC/2.03.11/x86_64-slc5-gcc43-opt/lib:/software/BES/bes6.6.4.p01/lcg/external/pcre/4.4/x86_64-slc5-gcc43-opt/lib:/software/BES/bes6.6.4.p01/packages/CLHEP/2.0.4.5/x86_64-slc5-gcc43-opt/lib:/software/BES/bes6.6.4.p01/lcg/external/Boost/1.39.0_python2.5/x86_64-slc5-gcc43-opt/lib:/software/BES/bes6.6.4.p01/lcg/external/ROOT/5.24.00b/x86_64-slc5-gcc43-opt/root/lib:/software/BES/bes6.6.4.p01/lcg/external/tcmalloc/1.4/x86_64-slc5-gcc43-opt/lib:/software/BES/bes6.6.4.p01/lcg/external/lapack/3.1.1/x86_64-slc5-gcc43-opt/lib:/software/BES/bes6.6.4.p01/lcg/external/blas/20070405/x86_64-slc5-gcc43-opt/lib:/software/BES/bes6.6.4.p01/lcg/external/uuid/1.38/x86_64-slc5-gcc43-opt/lib:/software/BES/bes6.6.4.p01/lcg/external/sqlite/3.6.11/x86_64-slc5-gcc43-opt/lib:/software/BES/bes6.6.4.p01/lcg/external/mysql/5.0.18/x86_64-slc5-gcc43-opt/lib:/software/BES/bes6.6.4.p01/lcg/external/XercesC/2.8.0/x86_64-slc5-gcc43-opt/lib:/software/BES/bes6.6.4.p01/lcg/external/castor/2.1.8-10/x86_64-slc5-gcc43-opt/usr/lib64:/software/BES/bes6.6.4.p01/lcg/external/CppUnit/1.12.1_p1/x86_64-slc5-gcc43-opt/lib:/software/BES/bes6.6.4.p01/contrib/x86_64-slc5-gcc43-opt/lib64:/software/BES/bes6.6.4.p01/contrib/x86_64-slc5-gcc43-opt/lib:/software/BES/bes6.6.4.p01/contrib/gcc43/lib64:/software/BES/bes6.6.4.p01/contrib/gcc43/lib:/software/BES/bes6.6.4.p01/packages/BesGDML/2.8.0/x86_64-slc5-gcc43-opt/CPPGDML/lib:/software/BES/bes6.6.4.p01/packages/DIM/dim_v19r11/x86_64-slc5-gcc43-opt/linux:/software/BES/bes6.6.4.p01/packages/geant4/4.9.3.p01/x86_64-slc5-gcc43-opt/geant4.9.3.p01/lib/Linux-g++:/software/BES/bes6.6.4.p01/packages/xmlrpc-c/xmlrpc-c-1.06.40/x86_64-slc5-gcc43-opt/lib:/software/BES/bes6.6.4.p01/packages/genbes/genbes-00-00-10/x86_64-slc5-gcc43-opt:/software/BES/bes6.6.4.p01/lcg/external/Python/2.5.4p2/x86_64-slc5-gcc43-opt/lib
Python_linkopts= -L$(Python_home)/lib -lpython$(Python_libversion) -lutil -lpthread 
Python_export_paths=$(Python_home)
MANPATH=/software/BES/bes6.6.4.p01/lcg/external/ROOT/5.24.00b/x86_64-slc5-gcc43-opt/root/man:/software/BES/bes6.6.4.p01/lcg/external/tcmalloc/1.4/x86_64-slc5-gcc43-opt/share/man:/software/BES/bes6.6.4.p01/lcg/external/Python/2.5.4p2/x86_64-slc5-gcc43-opt/share/man:/software/BES/bes6.6.4.p01/lcg/external/uuid/1.38/x86_64-slc5-gcc43-opt/man:/software/BES/bes6.6.4.p01/lcg/external/mysql/5.0.18/x86_64-slc5-gcc43-opt/man:/software/BES/bes6.6.4.p01/lcg/external/CppUnit/1.12.1_p1/x86_64-slc5-gcc43-opt/share/man:/software/BES/bes6.6.4.p01/lcg/external/pcre/4.4/x86_64-slc5-gcc43-opt/man:/software/BES/bes6.6.4.p01/lcg/external/gccxml/0.9.0_20090601/x86_64-slc5-gcc43-opt/share/man:/software/BES/bes6.6.4.p01/lcg/external/castor/2.1.8-10/x86_64-slc5-gcc43-opt/usr/share/man:/software/BES/bes6.6.4.p01/lcg/external/cernlib/2006a/x86_64-slc5-gcc43-opt/src/man:/software/BES/bes6.6.4.p01/lcg/external/ROOT/5.24.00b/src/root/man
tcmalloc_tag=$(tag)
TCMALLOCROOT=/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5/LCG_Interfaces/tcmalloc
tcmalloc_root=/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5/LCG_Interfaces/tcmalloc
TCMALLOCVERSION=v1
tcmalloc_cmtpath=/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5
tcmalloc_offset=LCG_Interfaces
tcmalloc_project=LCGCMT
tcmalloc_project_release=LCGCMT_57a_clhep2.0.4.5
tcmalloc_native_version=$(tcmalloc_config_version)
tcmalloc_home=$(LCG_external)/tcmalloc/$(tcmalloc_native_version)/$(LCG_system)
copyInclude=cp -Rup 
cmt_actions_constituents=       
cmt_actions_constituentsclean= new_rootsysclean TestProjectclean TestPackageclean qmtest_summarizeclean qmtest_runclean makeclean 
remove_command=$(cmt_uninstallarea_command)
dq="
BINDIR=$(tag)
vsDebug=2
merge_rootmap_cmd=python $(GaudiPolicy_root)/scripts/merge_files.py
libdirname=lib
bindirname=bin
cppdebugflags_s=-g
cppoptimized_s=-O2
cppprofiled_s=-pg
cppcoverage_s=-fprofile-arcs -ftest-coverage
cdebugflags_s=-g
ccoverage_s=-fprofile-arcs -ftest-coverage
fdebugflags= $(foptimized_s)
fdebugflags_s=-g
foptimized_s=-O2
fprofiled_s=-pg
fcoverage_s=-fprofile-arcs -ftest-coverage
linkcoverage_s=-lgcov
use_linkopts= $(cmt_installarea_linkopts)   $(McDecayModeSvc_linkopts)  $(McTruth_linkopts)  $(EventModel_linkopts)  $(Identifier_linkopts)  $(RelTable_linkopts)  $(BesPolicy_linkopts)  $(BesCxxPolicy_linkopts)  $(GaudiInterface_linkopts)  $(GaudiSvc_linkopts)  $(GaudiKernel_linkopts)  $(GaudiPolicy_linkopts)  $(Reflex_linkopts)  $(ROOT_linkopts)  $(Boost_linkopts)  $(BesFortranPolicy_linkopts)  $(BesCLHEP_linkopts)  $(CLHEP_linkopts)  $(HepMC_linkopts)  $(HepPDT_linkopts)  $(LCG_Settings_linkopts)  $(LCG_SettingsCompat_linkopts)  $(LCG_Configuration_linkopts)  $(BesExternalArea_linkopts) 
makeLinkMap=-Wl,-Map,Linux.map
componentshr_linkopts=-fPIC -ldl  -Wl,--no-undefined  -Wl,-z,max-page-size=0x1000  
libraryshr_linkopts=-fPIC -ldl  -Wl,--no-undefined  -Wl,-z,max-page-size=0x1000 
application_linkopts=-Wl,--export-dynamic 
genconfDir=/genConf/
merge_genconfDb_cmd=python $(GaudiPolicy_root)/scripts/merge_files.py
genconfig_configurableModuleName=GaudiKernel.Proxy
genconfig_configurableDefaultName=Configurable.DefaultName
genconfig_configurableAlgorithm=ConfigurableAlgorithm
genconfig_configurableAlgTool=ConfigurableAlgTool
genconfig_configurableAuditor=ConfigurableAuditor
genconfig_configurableService=ConfigurableService
use_GaudiSvc=GaudiSvc v* -no_auto_imports
strip_script=$(GAUDIPOLICYROOT)/scripts/StripPath
GenConfUser_script=genconfuser.py
POOLVERS=POOL_2_9_3
COOLVERS=COOL_2_8_3
CORALVERS=CORAL_2_3_4
ROOTVERS=5.24.00b
BoostVERS=1.39.0
uuidVERS=1.38
PCREVERS=4.4
GCCXMLVERS=0.9.0_20090601
AIDAVERS=3.2.1
XercesCVERS=2.8.0
GSLVERS=1.10
PythonVERS=2.5.4p2
HepMCVERS=2.03.11
QMtestVERS=2.4p1
LCGCMTVERS=57a
GAUDI_DOXY_HOME=/software/BES/bes6.6.4.p01/Gaudi/GAUDI_v21r6/x86_64-slc5-gcc43-clhep2.0.4.5/GaudiRelease/doc
config_command=cp 
BesCxxPolicy_pp_cppflags= -DHAVE_PRETTY_FUNCTION -DHAVE_LONG_LONG -DHAVE_BOOL -DHAVE_EXPLICIT -DHAVE_MUTABLE -DHAVE_SIGNED -DHAVE_TYPENAME -DHAVE_NEW_STYLE_CASTS -DHAVE_DYNAMIC_CAST -DHAVE_TYPEID -DHAVE_ANSI_TEMPLATE_INSTANTIATION -DHAVE_TEMPLATE_DEFAULT_ARGS -DHAVE_BROKEN_TEMPLATE_RESCOPE -DHAVE_TEMPLATE_NULL_ARGS -DHAVE_TEMPLATE_NULL_SPEC -DHAVE_TEMPLATE_PARTIAL_SPEC -DHAVE_MEMBER_TEMPLATES -DHAVE_ANSI_OPERATOR_ARROW -DHAVE_NAMESPACES -DHAVE_NAMESPACE_STD -DHAVE_NEW_IOSTREAMS -DHAVE_OSTREAM_CHAR_OVERLOAD -DHAVE_ITERATOR_TRAITS -DHAVE_ITERATOR -DHAVE_REVERSE_ITERATOR_STYLE -DHAVE_CXX_STDC_HEADERS '-DPACKAGE_VERSION=$(q2)$(version)$(q2)'  -DNDEBUG 
q2="
BesFortranPolicy_tag=$(tag)
BESFORTRANPOLICYROOT=/software/BES/bes6.6.4.p01/dist/6.6.4.p01/BesFortranPolicy/BesFortranPolicy-00-01-03
BesFortranPolicy_root=/software/BES/bes6.6.4.p01/dist/6.6.4.p01/BesFortranPolicy/BesFortranPolicy-00-01-03
BESFORTRANPOLICYVERSION=BesFortranPolicy-00-01-03
BesFortranPolicy_cmtpath=/software/BES/bes6.6.4.p01/dist/6.6.4.p01
BesFortranPolicy_project=BOSS
BesFortranPolicy_project_release=6.6.4.p01
f77_linkopts=-lgfortran -lnsl -lcrypt -ldl
f90_home=$(f90_home_linux)
for90=$(for90_linux)
f90pp=$(f90pp_linux)
f90flags=$(f90flags_linux)
f90ppflags=$(f90ppflags_linux)
f90comp=$(f90comp_linux)
f90link=$(f90link_linux)
f90_linkopts=$(f90_linkopts_linux)
BesFortranPolicy_linkopts=$(f77_linkopts)
BesFortranPolicy_export_paths=$(PGI_libset)
BesPolicy_scripts= -s=$(BESPOLICYROOT)/share -s=$(BESPOLICYROOT)/src symlink.sh inverse_symlink.sh get_files 
symlink_command=symlink.sh
symlinknew=$(symlink_command)
copy_command=cp -R
remote_launcher=ssh -f 
application_fragment=application
library_fragment=library
library_no_share_fragment=library_no_share
install_include_filter=*.h
GaudiInterface_tag=$(tag)
GAUDIINTERFACEROOT=/software/BES/bes6.6.4.p01/dist/6.6.4.p01/External/GaudiInterface/GaudiInterface-01-03-07
GaudiInterface_root=/software/BES/bes6.6.4.p01/dist/6.6.4.p01/External/GaudiInterface/GaudiInterface-01-03-07
GAUDIINTERFACEVERSION=GaudiInterface-01-03-07
GaudiInterface_cmtpath=/software/BES/bes6.6.4.p01/dist/6.6.4.p01
GaudiInterface_offset=External
GaudiInterface_project=BOSS
GaudiInterface_project_release=6.6.4.p01
GaudiKernel_tag=$(tag)
GAUDIKERNELROOT=/software/BES/bes6.6.4.p01/Gaudi/GAUDI_v21r6/x86_64-slc5-gcc43-clhep2.0.4.5/GaudiKernel
GaudiKernel_root=/software/BES/bes6.6.4.p01/Gaudi/GAUDI_v21r6/x86_64-slc5-gcc43-clhep2.0.4.5/GaudiKernel
GAUDIKERNELVERSION=v27r6
GaudiKernel_cmtpath=/software/BES/bes6.6.4.p01/Gaudi/GAUDI_v21r6/x86_64-slc5-gcc43-clhep2.0.4.5
GaudiKernel_project=GAUDI
GaudiKernel_project_release=x86_64-slc5-gcc43-clhep2.0.4.5
ROOT_tag=$(tag)
ROOTROOT=/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5/LCG_Interfaces/ROOT
ROOT_root=/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5/LCG_Interfaces/ROOT
ROOTVERSION=v1
ROOT_cmtpath=/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5
ROOT_offset=LCG_Interfaces
ROOT_project=LCGCMT
ROOT_project_release=LCGCMT_57a_clhep2.0.4.5
GCCXML_tag=$(tag)
GCCXMLROOT=/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5/LCG_Interfaces/GCCXML
GCCXML_root=/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5/LCG_Interfaces/GCCXML
GCCXMLVERSION=v1
GCCXML_cmtpath=/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5
GCCXML_offset=LCG_Interfaces
GCCXML_project=LCGCMT
GCCXML_project_release=LCGCMT_57a_clhep2.0.4.5
GCCXML_native_version=$(GCCXML_config_version)
GCCXML_home=$(LCG_external)/gccxml/$(GCCXML_native_version)/$(LCG_system)
GCCXML_name=gccxml
GCCXML_export_paths=$(GCCXML_home)/bin $(GCCXML_home)/share 
ROOT_native_version=$(ROOT_config_version)
ROOT_base=$(LCG_releases)/ROOT/$(ROOT_native_version)
ROOT_home=$(ROOT_base)/$(LCG_platform)/root
ROOT_linkopts=-L$(ROOT_home)/lib -lCore -lCint -lTree -lpthread  -lRIO
ROOT_Reflex_linkopts=-L$(ROOT_home)/lib -lReflex
ROOTSYS=/software/BES/bes6.6.4.p01/lcg/external/ROOT/5.24.00b/x86_64-slc5-gcc43-opt/root
ROOT_name=root
ROOT_header_file_filter=$(ROOT_home)/include
ROOT_header_file_stamp=$(ROOT_home)/include/Type.h
PYTHONPATH=/home/lliu/boss/Workarea-6.6.4.p01/InstallArea/python:/software/STCF/stcf1.0.0/InstallArea/python:/software/BES/bes6.6.4.p01/dist/6.6.4.p01/InstallArea/python:/software/BES/bes6.6.4.p01/Gaudi/GAUDI_v21r6/x86_64-slc5-gcc43-clhep2.0.4.5/InstallArea/python:/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5/InstallArea/python:/software/BES/bes6.6.4.p01/lcg/external/ROOT/5.24.00b/x86_64-slc5-gcc43-opt/root/lib
rootcint="$(ROOT_home)/bin/rootcint"
genmap_cmd=$(ROOTSYS)/bin/genmap
ROOT_export_paths= $(ROOT_home) 
Reflex_tag=$(tag)
REFLEXROOT=/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5/LCG_Interfaces/Reflex
Reflex_root=/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5/LCG_Interfaces/Reflex
REFLEXVERSION=v1
Reflex_cmtpath=/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5
Reflex_offset=LCG_Interfaces
Reflex_project=LCGCMT
Reflex_project_release=LCGCMT_57a_clhep2.0.4.5
Reflex_linkopts=$(ROOT_Reflex_linkopts)
genreflex_cmd=$(ROOT_home)/bin/genreflex
gccxmloptsval=--gccxml-compiler $(cpp_name) 
gccxmlopts=--gccxmlopt='$(gccxmloptsval)'
Boost_tag=$(tag)
BOOSTROOT=/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5/LCG_Interfaces/Boost
Boost_root=/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5/LCG_Interfaces/Boost
BOOSTVERSION=v1
Boost_cmtpath=/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5
Boost_offset=LCG_Interfaces
Boost_project=LCGCMT
Boost_project_release=LCGCMT_57a_clhep2.0.4.5
Boost_native_version=$(Boost_config_version)_python$(Python_config_version_twodigit)
Boost_home=$(LCG_external)/Boost/$(Boost_native_version)/$(LCG_system)
Boost_compiler_version=gcc43
Boost_linkopts=-L$(Boost_home)/lib  $(Boost_linkopts_system) $(Boost_linkopts_filesystem) $(Boost_linkopts_regex) $(Boost_linkopts_thread) 
Boost_linkopts_python= -lboost_python-$(Boost_compiler_version)-mt 
Boost_linkopts_system= -lboost_system-$(Boost_compiler_version)-mt 
Boost_linkopts_filesystem= -lboost_filesystem-$(Boost_compiler_version)-mt 
Boost_linkopts_filesystem_mt= -lboost_filesystem-$(Boost_compiler_version)-mt 
Boost_linkopts_iostreams= -lboost_iostreams-$(Boost_compiler_version)-mt 
Boost_linkopts_regex= -lboost_regex-$(Boost_compiler_version)-mt 
Boost_linkopts_thread= -lboost_thread-$(Boost_compiler_version)-mt 
Boost_linkopts_program_options= -lboost_program_options-$(Boost_compiler_version)-mt 
Boost_linkopts_serialization= -lboost_serialization-$(Boost_compiler_version)-mt 
Boost_linkopts_date_time= -lboost_date_time-$(Boost_compiler_version)-mt 
Boost_linkopts_graph= -lboost_graph-$(Boost_compiler_version)-mt 
Boost_header_file_filter=$(Boost_home)/include/boost-$(Boost_file_version)
Boost_header_file_stamp=$(Boost_home)/include/boost-$(Boost_file_version)/boost/any.hpp
Boost_export_paths=$(Boost_home)
includes= $(ppcmd)"/home/lliu/boss/Workarea-6.6.4.p01/InstallArea/include/McDecayModeSvc" $(ppcmd)"/home/lliu/boss/Workarea-6.6.4.p01/InstallArea/include" $(ppcmd)"/software/STCF/stcf1.0.0/InstallArea/include" $(ppcmd)"/software/BES/bes6.6.4.p01/dist/6.6.4.p01/InstallArea/include" $(ppcmd)"/software/BES/bes6.6.4.p01/Gaudi/GAUDI_v21r6/x86_64-slc5-gcc43-clhep2.0.4.5/InstallArea/include" $(use_includes)
GaudiKernel_linkopts= -lGaudiKernel 
GaudiKernel_stamps=${GAUDIKERNELROOT}/${BINDIR}/GaudiKernel.stamp 
GaudiKernel_linker_library=GaudiKernel
zip_GaudiKernel_python_modules_dependencies= GaudiKernel_python_init 
GaudiKernel_python_init_dependencies= GaudiKernel_python 
GaudiKernelDict_use_linkopts=$(use_linkopts)
GaudiKernelGen_dependencies=install_more_includes
genconfig_cmd=genconf.exe
GaudiSvc_tag=$(tag)
GAUDISVCROOT=/software/BES/bes6.6.4.p01/Gaudi/GAUDI_v21r6/x86_64-slc5-gcc43-clhep2.0.4.5/GaudiSvc
GaudiSvc_root=/software/BES/bes6.6.4.p01/Gaudi/GAUDI_v21r6/x86_64-slc5-gcc43-clhep2.0.4.5/GaudiSvc
GAUDISVCVERSION=v18r6
GaudiSvc_cmtpath=/software/BES/bes6.6.4.p01/Gaudi/GAUDI_v21r6/x86_64-slc5-gcc43-clhep2.0.4.5
GaudiSvc_project=GAUDI
GaudiSvc_project_release=x86_64-slc5-gcc43-clhep2.0.4.5
CLHEP_tag=$(tag)
CLHEPROOT=/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5/LCG_Interfaces/CLHEP
CLHEP_root=/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5/LCG_Interfaces/CLHEP
CLHEPVERSION=v1
CLHEP_cmtpath=/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5
CLHEP_offset=LCG_Interfaces
CLHEP_project=LCGCMT
CLHEP_project_release=LCGCMT_57a_clhep2.0.4.5
CLHEP_native_version=2.0.4.5
CLHEP_home=$(SITEROOT)/packages/CLHEP/2.0.4.5/x86_64-slc5-gcc43-opt
CLHEP_linkopts=-L$(CLHEP_home)/lib         -lCLHEP-Cast-$(CLHEP_native_version)        -lCLHEP-Evaluator-$(CLHEP_native_version)        -lCLHEP-Exceptions-$(CLHEP_native_version)        -lCLHEP-GenericFunctions-$(CLHEP_native_version)        -lCLHEP-Geometry-$(CLHEP_native_version)        -lCLHEP-Random-$(CLHEP_native_version)        -lCLHEP-RandomObjects-$(CLHEP_native_version)        -lCLHEP-RefCount-$(CLHEP_native_version)         -lCLHEP-Vector-$(CLHEP_native_version)        -lCLHEP-Matrix-$(CLHEP_native_version)   -L${ALIST_DIR}/x86_64-slc5-gcc43-opt -lAlist -L${STRING_DIR}/x86_64-slc5-gcc43-opt -lString 
CLHEP_name=clhep
CLHEP_export_paths=$(CLHEP_home)/include $(CLHEP_home)/lib
AIDA_tag=$(tag)
AIDAROOT=/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5/LCG_Interfaces/AIDA
AIDA_root=/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5/LCG_Interfaces/AIDA
AIDAVERSION=v1
AIDA_cmtpath=/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5
AIDA_offset=LCG_Interfaces
AIDA_project=LCGCMT
AIDA_project_release=LCGCMT_57a_clhep2.0.4.5
AIDA_native_version=$(AIDA_config_version)
AIDA_home=$(LCG_external)/AIDA/$(AIDA_native_version)/share
AIDA_export_paths=${AIDA_home}/src/cpp
PCRE_tag=$(tag)
PCREROOT=/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5/LCG_Interfaces/PCRE
PCRE_root=/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5/LCG_Interfaces/PCRE
PCREVERSION=v1
PCRE_cmtpath=/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5
PCRE_offset=LCG_Interfaces
PCRE_project=LCGCMT
PCRE_project_release=LCGCMT_57a_clhep2.0.4.5
PCRE_native_version=$(PCRE_config_version)
PCRE_home=$(LCG_external)/pcre/$(PCRE_native_version)/$(LCG_system)
PCRE_linkopts=-L$(PCRE_home)/lib -lpcre
PCRE_name=pcre
PCRE_export_paths=$(PCRE_home)/lib
BesCLHEP_tag=$(tag)
BESCLHEPROOT=/software/BES/bes6.6.4.p01/dist/6.6.4.p01/External/BesCLHEP/BesCLHEP-00-00-09
BesCLHEP_root=/software/BES/bes6.6.4.p01/dist/6.6.4.p01/External/BesCLHEP/BesCLHEP-00-00-09
BESCLHEPVERSION=BesCLHEP-00-00-09
BesCLHEP_cmtpath=/software/BES/bes6.6.4.p01/dist/6.6.4.p01
BesCLHEP_offset=External
BesCLHEP_project=BOSS
BesCLHEP_project_release=6.6.4.p01
HepMC_tag=$(tag)
HEPMCROOT=/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5/LCG_Interfaces/HepMC
HepMC_root=/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5/LCG_Interfaces/HepMC
HEPMCVERSION=v1
HepMC_cmtpath=/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5
HepMC_offset=LCG_Interfaces
HepMC_project=LCGCMT
HepMC_project_release=LCGCMT_57a_clhep2.0.4.5
HepMC_native_version=$(HepMC_config_version)
HepMC_home=$(LCG_external)/HepMC/$(HepMC_native_version)/$(LCG_system)
HepMC_linkopts=-L$(HepMC_home)/lib -lHepMC 
HepMC_export_paths=$(HepMC_home)/include $(HepMC_home)/lib
HepPDT_tag=$(tag)
HEPPDTROOT=/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5/LCG_Interfaces/HepPDT
HepPDT_root=/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5/LCG_Interfaces/HepPDT
HEPPDTVERSION=v1
HepPDT_cmtpath=/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5
HepPDT_offset=LCG_Interfaces
HepPDT_project=LCGCMT
HepPDT_project_release=LCGCMT_57a_clhep2.0.4.5
HepPDT_native_version=$(HepPDT_config_version)
HepPDT_home=$(LCG_external)/HepPDT/$(HepPDT_native_version)/$(LCG_system)
HepPDT_linkopts=-L$(HepPDT_home)/lib -lHepPDT -lHepPID 
HepPDT_export_paths=$(HepPDT_home)/include $(HepPDT_home)/lib
BesExternalArea_tag=$(tag)
BESEXTERNALAREAROOT=/software/BES/bes6.6.4.p01/dist/6.6.4.p01/External/BesExternalArea/BesExternalArea-00-00-21
BesExternalArea_root=/software/BES/bes6.6.4.p01/dist/6.6.4.p01/External/BesExternalArea/BesExternalArea-00-00-21
BESEXTERNALAREAVERSION=BesExternalArea-00-00-21
BesExternalArea_cmtpath=/software/BES/bes6.6.4.p01/dist/6.6.4.p01
BesExternalArea_offset=External
BesExternalArea_project=BOSS
BesExternalArea_project_release=6.6.4.p01
LCG_ROOT=${SITEROOT}/ExternalLib/lcg       BNL	   ${SITEROOT}/cernsw/lcg
LCG_EXTERNAL=${LCG_ROOT}/external
LCG_app_system=rh73_gcc32
LCG_ext_system=rh73_gcc32
BES_EXTERNAL=${SITEROOT}/packages
BESTESTDATA=${SITEROOT}/bes/offline/data/testfile
BESCALDATA=${SITEROOT}/data/${BES_RELEASE}
COMMON_PACKAGES=${SITEROOT}/packages
ALIST_DIR=${BES_EXTERNAL}/CLHEP/Alist/Alist-00-00-06
STRING_DIR=${BES_EXTERNAL}/CLHEP/String/String-00-00-05
CLHEP_pp_cppflags= -DCLHEP_MAX_MIN_DEFINED -DCLHEP_ABS_DEFINED -DCLHEP_SQR_DEFINED 
CLHEP_pp_fflags= -DCLHEP_MAX_MIN_DEFINED -DCLHEP_ABS_DEFINED -DCLHEP_SQR_DEFINED 
McTruth_tag=$(tag)
MCTRUTHROOT=/software/BES/bes6.6.4.p01/dist/6.6.4.p01/Event/McTruth/McTruth-00-02-19
McTruth_root=/software/BES/bes6.6.4.p01/dist/6.6.4.p01/Event/McTruth/McTruth-00-02-19
MCTRUTHVERSION=McTruth-00-02-19
McTruth_cmtpath=/software/BES/bes6.6.4.p01/dist/6.6.4.p01
McTruth_offset=Event
McTruth_project=BOSS
McTruth_project_release=6.6.4.p01
EventModel_tag=$(tag)
EVENTMODELROOT=/software/BES/bes6.6.4.p01/dist/6.6.4.p01/Event/EventModel/EventModel-01-05-31
EventModel_root=/software/BES/bes6.6.4.p01/dist/6.6.4.p01/Event/EventModel/EventModel-01-05-31
EVENTMODELVERSION=EventModel-01-05-31
EventModel_cmtpath=/software/BES/bes6.6.4.p01/dist/6.6.4.p01
EventModel_offset=Event
EventModel_project=BOSS
EventModel_project_release=6.6.4.p01
EventModel_linkopts= -L$(bin) -lEventModel  
Identifier_tag=$(tag)
IDENTIFIERROOT=/software/BES/bes6.6.4.p01/dist/6.6.4.p01/DetectorDescription/Identifier/Identifier-00-02-13
Identifier_root=/software/BES/bes6.6.4.p01/dist/6.6.4.p01/DetectorDescription/Identifier/Identifier-00-02-13
IDENTIFIERVERSION=Identifier-00-02-13
Identifier_cmtpath=/software/BES/bes6.6.4.p01/dist/6.6.4.p01
Identifier_offset=DetectorDescription
Identifier_project=BOSS
Identifier_project_release=6.6.4.p01
Identifier_linkopts= -L$(bin) -lIdentifier  
RelTable_tag=$(tag)
RELTABLEROOT=/software/BES/bes6.6.4.p01/dist/6.6.4.p01/Event/RelTable/RelTable-00-00-02
RelTable_root=/software/BES/bes6.6.4.p01/dist/6.6.4.p01/Event/RelTable/RelTable-00-00-02
RELTABLEVERSION=RelTable-00-00-02
RelTable_cmtpath=/software/BES/bes6.6.4.p01/dist/6.6.4.p01
RelTable_offset=Event
RelTable_project=BOSS
RelTable_project_release=6.6.4.p01
McTruth_linkopts= -L$(bin) -lMcTruth  
McDecayModeSvcLib_files=*.cxx
McDecayModeSvc_dependencies= McDecayModeSvcLib
McDecayModeSvcstamps= $(bin)/McDecayModeSvcLib.stamp $(bin)/McDecayModeSvcsetup.make 
McDecayModeSvc_linkopts= -L$(bin) -lMcDecayModeSvcLib
McDecayModeSvc_shlibflags=$(componentshr_linkopts) $(use_linkopts) 
GaudiPolicyDir=${GAUDIPOLICYROOT}/${BINDIR}
BesCxxPolicyDir=${BESCXXPOLICYROOT}/${BINDIR}
BesPolicyDir=${BESPOLICYROOT}/${BINDIR}
GaudiKernelDir=${GAUDIKERNELROOT}/${BINDIR}
GaudiSvcDir=${GAUDISVCROOT}/${BINDIR}
GaudiInterfaceDir=${GAUDIINTERFACEROOT}/${BINDIR}
EventModelDir=${EVENTMODELROOT}/${BINDIR}
IdentifierDir=${IDENTIFIERROOT}/${BINDIR}
RelTableDir=${RELTABLEROOT}/${BINDIR}
McTruthDir=${MCTRUTHROOT}/${BINDIR}
McDecayModeSvcDir=${MCDECAYMODESVCROOT}/${BINDIR}
old_dir=`echo $(McDecayModeSvc_project)/$(McDecayModeSvc_project_release) | sed -e 's#//#/#g'`
old_base=`echo $(McDecayModeSvc_cmtpath) | sed -e 's#/$(old_dir)##'`
sedcmd='s#$(old_base)##' -e 's#^/##' -e 's#/$##' -e 's#[^/]*#..#g'
new_base=`/bin/pwd | sed -e ${sedcmd}`
new_fincludes=`( echo $(includes) | sed -e 's#$(old_base)#$(new_base)#g')`
fincludes=`cmt show macro_value new_fincludes`
tag=x86_64-slc5-gcc43-opt
package=McDecayModeSvc
version=McDecayModeSvc-00-00-01
PACKAGE_ROOT=$(MCDECAYMODESVCROOT)
srcdir=../src
bin=../$(McDecayModeSvc_tag)/
BIN=/home/lliu/boss/Workarea-6.6.4.p01/Analysis/McDecayModeSvc/McDecayModeSvc-00-00-01/$(McDecayModeSvc_tag)/
javabin=../classes/
mgrdir=cmt
project=boss
cmt_installarea_paths= $(cmt_installarea_prefix)/$(CMTCONFIG)/bin $(GAUDI_installarea_prefix)/$(CMTCONFIG)/lib $(GAUDI_installarea_prefix)/share/lib $(GAUDI_installarea_prefix)/share/bin $(BOSS_installarea_prefix)/$(CMTCONFIG)/lib $(BOSS_installarea_prefix)/share/lib $(BOSS_installarea_prefix)/share/bin $(STCF_installarea_prefix)/$(CMTCONFIG)/lib $(STCF_installarea_prefix)/share/lib $(STCF_installarea_prefix)/share/bin $(boss_installarea_prefix)/$(CMTCONFIG)/lib $(boss_installarea_prefix)/share/lib $(boss_installarea_prefix)/share/bin
LCGCMT_installarea_prefix=$(cmt_installarea_prefix)
LCGCMT_installarea_prefix_remove=$(LCGCMT_installarea_prefix)
GAUDI_installarea_prefix=$(cmt_installarea_prefix)
GAUDI_installarea_prefix_remove=$(GAUDI_installarea_prefix)
BOSS_installarea_prefix=$(cmt_installarea_prefix)
BOSS_installarea_prefix_remove=$(BOSS_installarea_prefix)
STCF_installarea_prefix=$(cmt_installarea_prefix)
STCF_installarea_prefix_remove=$(STCF_installarea_prefix)
boss_installarea_prefix=$(cmt_installarea_prefix)
boss_installarea_prefix_remove=$(boss_installarea_prefix)
cmt_installarea_linkopts= -L/home/lliu/boss/Workarea-6.6.4.p01/$(boss_installarea_prefix)/$(CMTCONFIG)/lib  -L/software/STCF/stcf1.0.0/$(STCF_installarea_prefix)/$(CMTCONFIG)/lib  -L/software/BES/bes6.6.4.p01/dist/6.6.4.p01/$(BOSS_installarea_prefix)/$(CMTCONFIG)/lib  -L/software/BES/bes6.6.4.p01/Gaudi/GAUDI_v21r6/x86_64-slc5-gcc43-clhep2.0.4.5/$(GAUDI_installarea_prefix)/$(CMTCONFIG)/lib 
LCGCMT_home=/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5
GAUDI_home=/software/BES/bes6.6.4.p01/Gaudi/GAUDI_v21r6/x86_64-slc5-gcc43-clhep2.0.4.5
BOSS_home=/software/BES/bes6.6.4.p01/dist/6.6.4.p01
STCF_home=/software/STCF/stcf1.0.0
boss_home=/home/lliu/boss/Workarea-6.6.4.p01
boss_install_include= /home/lliu/boss/Workarea-6.6.4.p01/$(boss_installarea_prefix)/include 
STCF_install_include= /software/STCF/stcf1.0.0/$(STCF_installarea_prefix)/include 
BOSS_install_include= /software/BES/bes6.6.4.p01/dist/6.6.4.p01/$(BOSS_installarea_prefix)/include 
GAUDI_install_include= /software/BES/bes6.6.4.p01/Gaudi/GAUDI_v21r6/x86_64-slc5-gcc43-clhep2.0.4.5/$(GAUDI_installarea_prefix)/include 
GAUDI_install_python=/software/BES/bes6.6.4.p01/Gaudi/GAUDI_v21r6/x86_64-slc5-gcc43-clhep2.0.4.5/$(GAUDI_installarea_prefix)/python.zip
BOSS_install_python=/software/BES/bes6.6.4.p01/dist/6.6.4.p01/$(BOSS_installarea_prefix)/python.zip
STCF_install_python=/software/STCF/stcf1.0.0/$(STCF_installarea_prefix)/python.zip
boss_install_python=/home/lliu/boss/Workarea-6.6.4.p01/$(boss_installarea_prefix)/python.zip
GAUDI_install_pyd_module=/software/BES/bes6.6.4.p01/Gaudi/GAUDI_v21r6/x86_64-slc5-gcc43-clhep2.0.4.5/$(GAUDI_installarea_prefix)/$(tag)/python
BOSS_install_pyd_module=/software/BES/bes6.6.4.p01/dist/6.6.4.p01/$(BOSS_installarea_prefix)/$(tag)/python
STCF_install_pyd_module=/software/STCF/stcf1.0.0/$(STCF_installarea_prefix)/$(tag)/python
boss_install_pyd_module=/home/lliu/boss/Workarea-6.6.4.p01/$(boss_installarea_prefix)/$(tag)/python
scripts_offset=.
scripts_maindir=scripts
scripts_dir=$(scripts_maindir)
GAUDI_install_scripts=/software/BES/bes6.6.4.p01/Gaudi/GAUDI_v21r6/x86_64-slc5-gcc43-clhep2.0.4.5/$(GAUDI_installarea_prefix)/$(scripts_dir)
BOSS_install_scripts=/software/BES/bes6.6.4.p01/dist/6.6.4.p01/$(BOSS_installarea_prefix)/$(scripts_dir)
STCF_install_scripts=/software/STCF/stcf1.0.0/$(STCF_installarea_prefix)/$(scripts_dir)
boss_install_scripts=/home/lliu/boss/Workarea-6.6.4.p01/$(boss_installarea_prefix)/$(scripts_dir)
genconfInstallDir=/home/lliu/boss/Workarea-6.6.4.p01/$(boss_installarea_prefix)/python
JOBOPTSEARCHPATH=,/home/lliu/boss/Workarea-6.6.4.p01/InstallArea/jobOptions,/software/STCF/stcf1.0.0/InstallArea/jobOptions,/software/BES/bes6.6.4.p01/dist/6.6.4.p01/InstallArea/jobOptions,/software/BES/bes6.6.4.p01/Gaudi/GAUDI_v21r6/x86_64-slc5-gcc43-clhep2.0.4.5/InstallArea/jobOptions,/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5/InstallArea/jobOptions
DATAPATH=/home/lliu/boss/Workarea-6.6.4.p01/InstallArea/share:/software/STCF/stcf1.0.0/InstallArea/share:/software/BES/bes6.6.4.p01/dist/6.6.4.p01/InstallArea/share:/software/BES/bes6.6.4.p01/Gaudi/GAUDI_v21r6/x86_64-slc5-gcc43-clhep2.0.4.5/InstallArea/share:/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5/InstallArea/share:/software/BES/bes6.6.4.p01/Gaudi/GAUDI_v21r6/x86_64-slc5-gcc43-clhep2.0.4.5/PartPropSvc/share
XMLPATH=/home/lliu/boss/Workarea-6.6.4.p01/InstallArea/XML:/software/STCF/stcf1.0.0/InstallArea/XML:/software/BES/bes6.6.4.p01/dist/6.6.4.p01/InstallArea/XML:/software/BES/bes6.6.4.p01/Gaudi/GAUDI_v21r6/x86_64-slc5-gcc43-clhep2.0.4.5/InstallArea/XML:/software/BES/bes6.6.4.p01/lcg/app/releases/LCGCMT/LCGCMT_57a_clhep2.0.4.5/InstallArea/XML
constituents= install_includes  McDecayModeSvcLib McDecayModeSvc config install_includes 
CMTINSTALLAREA=/home/lliu/boss/Workarea-6.6.4.p01/$(cmt_installarea_prefix)
use_requirements=requirements $(CMT_root)/mgr/requirements $(McTruth_root)/cmt/requirements $(EventModel_root)/cmt/requirements $(Identifier_root)/cmt/requirements $(RelTable_root)/cmt/requirements $(BesPolicy_root)/cmt/requirements $(BesCxxPolicy_root)/cmt/requirements $(GaudiInterface_root)/cmt/requirements $(GaudiSvc_root)/cmt/requirements $(GaudiKernel_root)/cmt/requirements $(GaudiPolicy_root)/cmt/requirements $(Reflex_root)/cmt/requirements $(ROOT_root)/cmt/requirements $(Boost_root)/cmt/requirements $(Python_root)/cmt/requirements $(tcmalloc_root)/cmt/requirements $(BesFortranPolicy_root)/cmt/requirements $(GCCXML_root)/cmt/requirements $(BesCLHEP_root)/cmt/requirements $(CLHEP_root)/cmt/requirements $(AIDA_root)/cmt/requirements $(PCRE_root)/cmt/requirements $(HepMC_root)/cmt/requirements $(HepPDT_root)/cmt/requirements $(LCG_Settings_root)/cmt/requirements $(LCG_SettingsCompat_root)/cmt/requirements $(LCG_Configuration_root)/cmt/requirements $(BesExternalArea_root)/cmt/requirements 
use_includes= $(ppcmd)"/software/BES/bes6.6.4.p01/dist/6.6.4.p01/Event/McTruth/McTruth-00-02-19/McTruth" $(ppcmd)"/software/BES/bes6.6.4.p01/dist/6.6.4.p01/InstallArea/include/McTruth" $(ppcmd)"/software/BES/bes6.6.4.p01/dist/6.6.4.p01/Event/EventModel/EventModel-01-05-31" $(ppcmd)"/software/BES/bes6.6.4.p01/dist/6.6.4.p01/InstallArea/include/EventModel" $(ppcmd)"/software/BES/bes6.6.4.p01/dist/6.6.4.p01/DetectorDescription/Identifier/Identifier-00-02-13" $(ppcmd)"/software/BES/bes6.6.4.p01/dist/6.6.4.p01/InstallArea/include/Identifier" $(ppcmd)"/software/BES/bes6.6.4.p01/dist/6.6.4.p01/Event/RelTable/RelTable-00-00-02" $(ppcmd)"/software/BES/bes6.6.4.p01/dist/6.6.4.p01/InstallArea/include/RelTable" $(ppcmd)"/software/BES/bes6.6.4.p01/dist/6.6.4.p01/BesCxxPolicy/BesCxxPolicy-00-01-01" $(ppcmd)"/software/BES/bes6.6.4.p01/lcg/external/ROOT/5.24.00b/x86_64-slc5-gcc43-opt/root/include" $(ppcmd)"/software/BES/bes6.6.4.p01/lcg/external/ROOT/5.24.00b/x86_64-slc5-gcc43-opt/root/include" $(ppcmd)"/software/BES/bes6.6.4.p01/lcg/external/Boost/1.39.0_python2.5/x86_64-slc5-gcc43-opt/include/boost-1_39" $(ppcmd)"$(BesFortranPolicy_root)/src" $(ppcmd)"$(BesCLHEP_root)/src" $(ppcmd)"/software/BES/bes6.6.4.p01/packages/CLHEP/Alist/Alist-00-00-06" $(ppcmd)"/software/BES/bes6.6.4.p01/packages/CLHEP/String/String-00-00-05" $(ppcmd)"/software/BES/bes6.6.4.p01/packages/CLHEP/2.0.4.5/x86_64-slc5-gcc43-opt/include" $(ppcmd)"/software/BES/bes6.6.4.p01/lcg/external/HepMC/2.03.11/x86_64-slc5-gcc43-opt/include" $(ppcmd)"/software/BES/bes6.6.4.p01/lcg/external/HepPDT/2.05.04/x86_64-slc5-gcc43-opt/include" $(ppcmd)"$(LCG_SettingsCompat_root)/src" $(ppcmd)"$(BesExternalArea_root)/src" 
use_fincludes= $(use_includes)
use_stamps=  $(McDecayModeSvc_stamps)  $(McTruth_stamps)  $(EventModel_stamps)  $(Identifier_stamps)  $(RelTable_stamps)  $(BesPolicy_stamps)  $(BesCxxPolicy_stamps)  $(GaudiInterface_stamps)  $(GaudiSvc_stamps)  $(GaudiKernel_stamps)  $(GaudiPolicy_stamps)  $(Reflex_stamps)  $(ROOT_stamps)  $(Boost_stamps)  $(BesFortranPolicy_stamps)  $(BesCLHEP_stamps)  $(CLHEP_stamps)  $(HepMC_stamps)  $(HepPDT_stamps)  $(LCG_Settings_stamps)  $(LCG_SettingsCompat_stamps)  $(LCG_Configuration_stamps)  $(BesExternalArea_stamps) 
use_cflags=  $(McDecayModeSvc_cflags)  $(McTruth_cflags)  $(EventModel_cflags)  $(Identifier_cflags)  $(RelTable_cflags)  $(BesPolicy_cflags)  $(BesCxxPolicy_cflags)  $(GaudiInterface_cflags)  $(GaudiSvc_cflags)  $(GaudiKernel_cflags)  $(GaudiPolicy_cflags)  $(Reflex_cflags)  $(ROOT_cflags)  $(Boost_cflags)  $(BesFortranPolicy_cflags)  $(BesCLHEP_cflags)  $(CLHEP_cflags)  $(HepMC_cflags)  $(HepPDT_cflags)  $(LCG_Settings_cflags)  $(LCG_SettingsCompat_cflags)  $(LCG_Configuration_cflags)  $(BesExternalArea_cflags) 
use_pp_cflags=  $(McDecayModeSvc_pp_cflags)  $(McTruth_pp_cflags)  $(EventModel_pp_cflags)  $(Identifier_pp_cflags)  $(RelTable_pp_cflags)  $(BesPolicy_pp_cflags)  $(BesCxxPolicy_pp_cflags)  $(GaudiInterface_pp_cflags)  $(GaudiSvc_pp_cflags)  $(GaudiKernel_pp_cflags)  $(GaudiPolicy_pp_cflags)  $(Reflex_pp_cflags)  $(ROOT_pp_cflags)  $(Boost_pp_cflags)  $(BesFortranPolicy_pp_cflags)  $(BesCLHEP_pp_cflags)  $(CLHEP_pp_cflags)  $(HepMC_pp_cflags)  $(HepPDT_pp_cflags)  $(LCG_Settings_pp_cflags)  $(LCG_SettingsCompat_pp_cflags)  $(LCG_Configuration_pp_cflags)  $(BesExternalArea_pp_cflags) 
use_cppflags=  $(McDecayModeSvc_cppflags)  $(McTruth_cppflags)  $(EventModel_cppflags)  $(Identifier_cppflags)  $(RelTable_cppflags)  $(BesPolicy_cppflags)  $(BesCxxPolicy_cppflags)  $(GaudiInterface_cppflags)  $(GaudiSvc_cppflags)  $(GaudiKernel_cppflags)  $(GaudiPolicy_cppflags)  $(Reflex_cppflags)  $(ROOT_cppflags)  $(Boost_cppflags)  $(BesFortranPolicy_cppflags)  $(BesCLHEP_cppflags)  $(CLHEP_cppflags)  $(HepMC_cppflags)  $(HepPDT_cppflags)  $(LCG_Settings_cppflags)  $(LCG_SettingsCompat_cppflags)  $(LCG_Configuration_cppflags)  $(BesExternalArea_cppflags) 
use_pp_cppflags=  $(McDecayModeSvc_pp_cppflags)  $(McTruth_pp_cppflags)  $(EventModel_pp_cppflags)  $(Identifier_pp_cppflags)  $(RelTable_pp_cppflags)  $(BesPolicy_pp_cppflags)  $(BesCxxPolicy_pp_cppflags)  $(GaudiInterface_pp_cppflags)  $(GaudiSvc_pp_cppflags)  $(GaudiKernel_pp_cppflags)  $(GaudiPolicy_pp_cppflags)  $(Reflex_pp_cppflags)  $(ROOT_pp_cppflags)  $(Boost_pp_cppflags)  $(BesFortranPolicy_pp_cppflags)  $(BesCLHEP_pp_cppflags)  $(CLHEP_pp_cppflags)  $(HepMC_pp_cppflags)  $(HepPDT_pp_cppflags)  $(LCG_Settings_pp_cppflags)  $(LCG_SettingsCompat_pp_cppflags)  $(LCG_Configuration_pp_cppflags)  $(BesExternalArea_pp_cppflags) 
use_fflags=  $(McDecayModeSvc_fflags)  $(McTruth_fflags)  $(EventModel_fflags)  $(Identifier_fflags)  $(RelTable_fflags)  $(BesPolicy_fflags)  $(BesCxxPolicy_fflags)  $(GaudiInterface_fflags)  $(GaudiSvc_fflags)  $(GaudiKernel_fflags)  $(GaudiPolicy_fflags)  $(Reflex_fflags)  $(ROOT_fflags)  $(Boost_fflags)  $(BesFortranPolicy_fflags)  $(BesCLHEP_fflags)  $(CLHEP_fflags)  $(HepMC_fflags)  $(HepPDT_fflags)  $(LCG_Settings_fflags)  $(LCG_SettingsCompat_fflags)  $(LCG_Configuration_fflags)  $(BesExternalArea_fflags) 
use_pp_fflags=  $(McDecayModeSvc_pp_fflags)  $(McTruth_pp_fflags)  $(EventModel_pp_fflags)  $(Identifier_pp_fflags)  $(RelTable_pp_fflags)  $(BesPolicy_pp_fflags)  $(BesCxxPolicy_pp_fflags)  $(GaudiInterface_pp_fflags)  $(GaudiSvc_pp_fflags)  $(GaudiKernel_pp_fflags)  $(GaudiPolicy_pp_fflags)  $(Reflex_pp_fflags)  $(ROOT_pp_fflags)  $(Boost_pp_fflags)  $(BesFortranPolicy_pp_fflags)  $(BesCLHEP_pp_fflags)  $(CLHEP_pp_fflags)  $(HepMC_pp_fflags)  $(HepPDT_pp_fflags)  $(LCG_Settings_pp_fflags)  $(LCG_SettingsCompat_pp_fflags)  $(LCG_Configuration_pp_fflags)  $(BesExternalArea_pp_fflags) 
use_libraries= $(McTruth_libraries)  $(EventModel_libraries)  $(Identifier_libraries)  $(RelTable_libraries)  $(BesPolicy_libraries)  $(BesCxxPolicy_libraries)  $(GaudiInterface_libraries)  $(GaudiSvc_libraries)  $(GaudiKernel_libraries)  $(GaudiPolicy_libraries)  $(Reflex_libraries)  $(ROOT_libraries)  $(Boost_libraries)  $(Python_libraries)  $(tcmalloc_libraries)  $(BesFortranPolicy_libraries)  $(GCCXML_libraries)  $(BesCLHEP_libraries)  $(CLHEP_libraries)  $(AIDA_libraries)  $(PCRE_libraries)  $(HepMC_libraries)  $(HepPDT_libraries)  $(LCG_Settings_libraries)  $(LCG_SettingsCompat_libraries)  $(LCG_Configuration_libraries)  $(BesExternalArea_libraries) 
McDecayModeSvcLib_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
McDecayModeSvcLib_use_linkopts=  $(McDecayModeSvc_linkopts)  $(McTruth_linkopts)  $(EventModel_linkopts)  $(Identifier_linkopts)  $(RelTable_linkopts)  $(BesPolicy_linkopts)  $(BesCxxPolicy_linkopts)  $(GaudiInterface_linkopts)  $(GaudiSvc_linkopts)  $(GaudiKernel_linkopts)  $(GaudiPolicy_linkopts)  $(Reflex_linkopts)  $(ROOT_linkopts)  $(Boost_linkopts)  $(BesFortranPolicy_linkopts)  $(BesCLHEP_linkopts)  $(CLHEP_linkopts)  $(HepMC_linkopts)  $(HepPDT_linkopts)  $(LCG_Settings_linkopts)  $(LCG_SettingsCompat_linkopts)  $(LCG_Configuration_linkopts)  $(BesExternalArea_linkopts) 
McDecayModeSvc_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
McDecayModeSvc_use_linkopts=  $(McDecayModeSvc_linkopts)  $(McTruth_linkopts)  $(EventModel_linkopts)  $(Identifier_linkopts)  $(RelTable_linkopts)  $(BesPolicy_linkopts)  $(BesCxxPolicy_linkopts)  $(GaudiInterface_linkopts)  $(GaudiSvc_linkopts)  $(GaudiKernel_linkopts)  $(GaudiPolicy_linkopts)  $(Reflex_linkopts)  $(ROOT_linkopts)  $(Boost_linkopts)  $(BesFortranPolicy_linkopts)  $(BesCLHEP_linkopts)  $(CLHEP_linkopts)  $(HepMC_linkopts)  $(HepPDT_linkopts)  $(LCG_Settings_linkopts)  $(LCG_SettingsCompat_linkopts)  $(LCG_Configuration_linkopts)  $(BesExternalArea_linkopts) 
config_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
install_includes_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
make_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
CompilePython_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
qmtest_run_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
qmtest_summarize_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
TestPackage_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
TestProject_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
new_rootsys_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
all_constituents= $(constituents)
constituentsclean= install_includesclean configclean McDecayModeSvcclean McDecayModeSvcLibclean 
all_constituentsclean= $(constituentsclean)
